### ISSUE TITLE
ssh -o StrictHostKeyChecking=accept-new does not work on metanet

### ISSUE THREAD

**Issue by deflox** [FlorianMoser/plesk-deployer#3]
Thank you for this recipe. Although I couldn't use it directly for my use case it gave me good hints where the my issues were coming from and I was able to fix them. 😊

Apparently at least since deployer version `7.x`, the `GIT_SSH_COMMAND` environment variable is specifically set to `ssh -o StrictHostKeyChecking=accept-new` (see [here](https://github.com/deployphp/deployer/blob/master/recipe/deploy/update_code.php#L84)). Overriding this environment variable causes `git fetch` to use this specified command instead of the default `ssh` command (see [here](https://git-scm.com/docs/git#Documentation/git.txt-codeGITSSHCOMMANDcode)). Unfortunately it looks like this option is not supported on metanet which causes the deployment to fail. So to fix this you have to set it back to `ssh`:
```php
set('git_ssh_command', 'ssh');
```

This option would be useful though since it would just add new hosts to the known hosts file without asking and only asks in case an existing host changes... :) So one has to make sure the repository host is already added to the known host file before doing the deployment otherwise it will most likely fail too.

I know this is not really an direct issue for this repository since it appears to be targeted more generally to plesk hosts but since it is linked from the metanet SSH support page I though I could document this as a hint in case anyone faces the same issue.

**Comment by FlorianMoser** [comment]
I'm glad the recipe is of help 😃 

Thank you very much for mentioning this issue! I added it to the [description of common problems](https://github.com/FlorianMoser/plesk-deployer#common-problems-while-deploying-to-chroot-environment) in the README file.
